services:
  # Your Python Application our image
  backendservice:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/apps
    environment:
      - DATABASE_URL=postgresql://db_user:db_password@db:5432/my_database
    depends_on:
      db:
        condition: service_healthy

  # The Database Service(External hub image)
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  postgres_data:
